baseURL = "https://example.com"
title = "小备份大整理"
theme = "hugo-theme-bootstrap"
copyright = "Copyright © 2016-{year} Razon Yang. All Rights Reserved."

# Multilingual mode
defaultContentLanguage = "zh-cn"
# defaultContentLanguageInSubdir = true # If you use only one language comment this option
#disableLanguages = ["fr", "zh-cn" ,"zh-tw"] # For disable one or more language

# Pagination
paginate = 16
# paginatePath = "page"

# Disqus
# disqusShortname = "yourdiscussshortname"

# Google analytics
# googleAnalytics = "UA-123-45"

enableRobotsTXT = true

enableEmoji = true

# hasCJKLanguage = true # Turn on it if your content contains Chinese/Japanese/Korean Languages.

pygmentsUseClasses = true

[blackfriday]
  hrefTargetBlank = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
math = true # Enable math globally.
toc = true # Disable TOC globally.
breadcrumb = false # Disable breadcrumb
diagram = true
